using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Grpc.Base.Contracts
{
    //this interface is implemented by classes generated by grpc from proto definitions
    //need this interface for method that handles retrieval by id
   public interface IItemInfoResponse
    {
        bool NoItem { get; set; }
    }
}
