using AutoMapper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Account.API.Helpers
{
    //this helper class contains methods shared by grpc services
    public static class GrpcServiceHelpers
    {
        //this method adds list of items returned from domain logic layer to grpc reponse
        //T - object with list of items
        //D - DTO from domain logic layer
        //I - item which is in list
        public static async Task<T> GetItems<T, D, I>(Func<Task<ICollection<D>>> action, IMapper mapper)
           where T : IItemList<I>, new()
        {
            //get items from domain logic service
            var items = await action();
            //map collection of dtos to collection of objects generated by grpc
            var itemList = mapper.Map<ICollection<D>, ICollection<I>>(items);
            //create grpc response that contains list of items
            var response = new T();
            //add items to the list
            response.Items.Add(itemList);
            return response;
        }
    }
}
